name: Hello World and Install Packages

on: [push]

jobs:
  build-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print message
        run: echo "Hello World"
      - name: Install packages
        run: npm install
