name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: https://github.com/Omprakashsurwase/github-Action.git

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .

      - name: Run Docker container
        run: |
          docker run --name my-container my-docker-image

      - name: Check output
        run: |
          docker logs my-container

      - name: Cleanup
        run: |
          docker stop my-container
          docker rm my-container
