name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create app.js
        run: |
          echo 'console.log("Hello, World! This is my application running inside a Docker container.");' > app.js

      - name: Create Dockerfile
        run: |
          echo 'FROM centos:7' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY app.js .' >> Dockerfile
          echo 'CMD ["node", "app.js"]' >> Dockerfile

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .

      - name: List running containers
        run: |
          docker ps 

      - name: List Docker images
        run: |
          docker images  # List all Docker i

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .
          docker run --name my-container -d my-docker-image


      - name: Check output
        run: |
          docker logs my-container

      - name: Cleanup
        run: |
          docker stop my-container
          docker rm my-container
