name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Dockerfile
        run: |
          echo 'FROM centos:7' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY app.sh .' >> Dockerfile
          echo 'RUN yum -y update && >> Dockerfile
          echo 'CMD ["./app.sh"]' >> Dockerfile

      - name: Create app.sh
        run: |
          echo '#!/bin/bash' > app.sh
          echo 'echo "Hello, World! This is my application running inside a Docker container."' >> app.sh
          chmod +x app.sh

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .

      - name: Run Docker container
        run: |
          docker run --name my-container my-docker-image

      - name: Check output
        run: |
          docker logs my-container

      - name: Cleanup
        run: |
          docker stop my-container
          docker rm my-container
