name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t my-docker-image .

      - name: Run Docker container
        run: |
          docker run --name my-container -d my-docker-image

      - name: Install packages and run code
        run: |
          docker exec my-container yum install -y tree vi
          docker exec my-container yum update -y
          docker exec my-container sh -c "cd /path/to/your/code && ./your_build_command"

      - name: Cleanup
        run: |
          docker stop my-container
          docker rm my-container
